# Site settings
title: "M3PGS/2E0PGS blog"
email: 2E0PGS@gmail.com
description: "Ham radio, Programming, Networks, Electronics, FOSS, GNU/Linux, Trance and Ale."
baseurl: "https://2e0pgs.github.io/blog"
url: "https://2e0pgs.github.io/blog/"
title_description: "Ham radio, Programming, Networks, Electronics, FOSS, GNU/Linux, Trance and Ale."
title_image: "https://secure.gravatar.com/avatar/b8a87d182b1468a827a92a27f465f15b?s=500&d=mm"
google_analytics:
disqus_account: 2E0PGS
github_repository: https://github.com/2e0pgs/blog
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: M3PGS
github_username:  2E0PGS
instagram_username:
reddit_username:
linkedin_link:
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: "Theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right:

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
